// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: src/github.com/vijayshukla30/NexthoughtsPortal/Session/proto/session-data.proto

package sessiondata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SessionData service

type SessionDataService interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...client.CallOption) (*RemoveResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
	ListByUser(ctx context.Context, in *ListByUserRequest, opts ...client.CallOption) (*ListResponse, error)
	ListByTime(ctx context.Context, in *ListByTimeRequest, opts ...client.CallOption) (*ListResponse, error)
}

type sessionDataService struct {
	c    client.Client
	name string
}

func NewSessionDataService(name string, c client.Client) SessionDataService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "sessiondata"
	}
	return &sessionDataService{
		c:    c,
		name: name,
	}
}

func (c *sessionDataService) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.name, "SessionData.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionDataService) Remove(ctx context.Context, in *RemoveRequest, opts ...client.CallOption) (*RemoveResponse, error) {
	req := c.c.NewRequest(c.name, "SessionData.Remove", in)
	out := new(RemoveResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionDataService) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.name, "SessionData.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionDataService) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.name, "SessionData.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionDataService) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "SessionData.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionDataService) ListByUser(ctx context.Context, in *ListByUserRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "SessionData.ListByUser", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionDataService) ListByTime(ctx context.Context, in *ListByTimeRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "SessionData.ListByTime", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SessionData service

type SessionDataHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Remove(context.Context, *RemoveRequest, *RemoveResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	List(context.Context, *ListRequest, *ListResponse) error
	ListByUser(context.Context, *ListByUserRequest, *ListResponse) error
	ListByTime(context.Context, *ListByTimeRequest, *ListResponse) error
}

func RegisterSessionDataHandler(s server.Server, hdlr SessionDataHandler, opts ...server.HandlerOption) error {
	type sessionData interface {
		Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error
		Remove(ctx context.Context, in *RemoveRequest, out *RemoveResponse) error
		Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error
		Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error
		List(ctx context.Context, in *ListRequest, out *ListResponse) error
		ListByUser(ctx context.Context, in *ListByUserRequest, out *ListResponse) error
		ListByTime(ctx context.Context, in *ListByTimeRequest, out *ListResponse) error
	}
	type SessionData struct {
		sessionData
	}
	h := &sessionDataHandler{hdlr}
	return s.Handle(s.NewHandler(&SessionData{h}, opts...))
}

type sessionDataHandler struct {
	SessionDataHandler
}

func (h *sessionDataHandler) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.SessionDataHandler.Create(ctx, in, out)
}

func (h *sessionDataHandler) Remove(ctx context.Context, in *RemoveRequest, out *RemoveResponse) error {
	return h.SessionDataHandler.Remove(ctx, in, out)
}

func (h *sessionDataHandler) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.SessionDataHandler.Update(ctx, in, out)
}

func (h *sessionDataHandler) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.SessionDataHandler.Read(ctx, in, out)
}

func (h *sessionDataHandler) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.SessionDataHandler.List(ctx, in, out)
}

func (h *sessionDataHandler) ListByUser(ctx context.Context, in *ListByUserRequest, out *ListResponse) error {
	return h.SessionDataHandler.ListByUser(ctx, in, out)
}

func (h *sessionDataHandler) ListByTime(ctx context.Context, in *ListByTimeRequest, out *ListResponse) error {
	return h.SessionDataHandler.ListByTime(ctx, in, out)
}
