// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/github.com/vijayshukla30/NexthoughtsPortal/Session/proto/session-data.proto

package sessiondata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Session struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Created              int64    `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc26e0e3c2f6a1c, []int{0}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Session) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Session) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Session) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Session) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type CreateRequest struct {
	Session              *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc26e0e3c2f6a1c, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type CreateResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc26e0e3c2f6a1c, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RemoveRequest struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRequest) Reset()         { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()    {}
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc26e0e3c2f6a1c, []int{3}
}

func (m *RemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRequest.Unmarshal(m, b)
}
func (m *RemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRequest.Marshal(b, m, deterministic)
}
func (m *RemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRequest.Merge(m, src)
}
func (m *RemoveRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRequest.Size(m)
}
func (m *RemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRequest proto.InternalMessageInfo

func (m *RemoveRequest) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

type RemoveResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveResponse) Reset()         { *m = RemoveResponse{} }
func (m *RemoveResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveResponse) ProtoMessage()    {}
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc26e0e3c2f6a1c, []int{4}
}

func (m *RemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveResponse.Unmarshal(m, b)
}
func (m *RemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveResponse.Marshal(b, m, deterministic)
}
func (m *RemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveResponse.Merge(m, src)
}
func (m *RemoveResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveResponse.Size(m)
}
func (m *RemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveResponse proto.InternalMessageInfo

func (m *RemoveResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateRequest struct {
	Session              *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc26e0e3c2f6a1c, []int{5}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type UpdateResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc26e0e3c2f6a1c, []int{6}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ReadRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc26e0e3c2f6a1c, []int{7}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type ReadResponse struct {
	Session              *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc26e0e3c2f6a1c, []int{8}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc26e0e3c2f6a1c, []int{9}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Sessions             []*Session `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc26e0e3c2f6a1c, []int{10}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetSessions() []*Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type ListByUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListByUserRequest) Reset()         { *m = ListByUserRequest{} }
func (m *ListByUserRequest) String() string { return proto.CompactTextString(m) }
func (*ListByUserRequest) ProtoMessage()    {}
func (*ListByUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc26e0e3c2f6a1c, []int{11}
}

func (m *ListByUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListByUserRequest.Unmarshal(m, b)
}
func (m *ListByUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListByUserRequest.Marshal(b, m, deterministic)
}
func (m *ListByUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListByUserRequest.Merge(m, src)
}
func (m *ListByUserRequest) XXX_Size() int {
	return xxx_messageInfo_ListByUserRequest.Size(m)
}
func (m *ListByUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListByUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListByUserRequest proto.InternalMessageInfo

func (m *ListByUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ListByTimeRequest struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListByTimeRequest) Reset()         { *m = ListByTimeRequest{} }
func (m *ListByTimeRequest) String() string { return proto.CompactTextString(m) }
func (*ListByTimeRequest) ProtoMessage()    {}
func (*ListByTimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc26e0e3c2f6a1c, []int{12}
}

func (m *ListByTimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListByTimeRequest.Unmarshal(m, b)
}
func (m *ListByTimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListByTimeRequest.Marshal(b, m, deterministic)
}
func (m *ListByTimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListByTimeRequest.Merge(m, src)
}
func (m *ListByTimeRequest) XXX_Size() int {
	return xxx_messageInfo_ListByTimeRequest.Size(m)
}
func (m *ListByTimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListByTimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListByTimeRequest proto.InternalMessageInfo

func (m *ListByTimeRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *ListByTimeRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func init() {
	proto.RegisterType((*Session)(nil), "sessiondata.Session")
	proto.RegisterType((*CreateRequest)(nil), "sessiondata.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "sessiondata.CreateResponse")
	proto.RegisterType((*RemoveRequest)(nil), "sessiondata.RemoveRequest")
	proto.RegisterType((*RemoveResponse)(nil), "sessiondata.RemoveResponse")
	proto.RegisterType((*UpdateRequest)(nil), "sessiondata.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "sessiondata.UpdateResponse")
	proto.RegisterType((*ReadRequest)(nil), "sessiondata.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "sessiondata.ReadResponse")
	proto.RegisterType((*ListRequest)(nil), "sessiondata.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "sessiondata.ListResponse")
	proto.RegisterType((*ListByUserRequest)(nil), "sessiondata.ListByUserRequest")
	proto.RegisterType((*ListByTimeRequest)(nil), "sessiondata.ListByTimeRequest")
}

func init() {
	proto.RegisterFile("src/github.com/vijayshukla30/NexthoughtsPortal/Session/proto/session-data.proto", fileDescriptor_5cc26e0e3c2f6a1c)
}

var fileDescriptor_5cc26e0e3c2f6a1c = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xed, 0x6e, 0xd3, 0x40,
	0x10, 0x54, 0xe2, 0xc4, 0xa1, 0xeb, 0xa6, 0x82, 0x53, 0x84, 0x4c, 0x40, 0x28, 0xf2, 0xaf, 0x8a,
	0xaa, 0x76, 0xd5, 0xfe, 0xac, 0x44, 0x09, 0x54, 0x42, 0x48, 0x08, 0x90, 0xa1, 0x0f, 0x70, 0xcd,
	0xad, 0x12, 0x43, 0x12, 0x07, 0xef, 0xb9, 0xd0, 0xd7, 0xe5, 0x49, 0xd0, 0x7d, 0xd8, 0x89, 0x0f,
	0x43, 0x41, 0xfc, 0xf3, 0xee, 0xce, 0xce, 0xee, 0xde, 0x8c, 0x0c, 0xef, 0xa9, 0x98, 0x25, 0xf3,
	0x4c, 0x2e, 0xca, 0xeb, 0x78, 0x96, 0xaf, 0x92, 0x9b, 0xec, 0x33, 0xbf, 0xa5, 0x45, 0xf9, 0x65,
	0xc9, 0xcf, 0x4e, 0x92, 0x77, 0xf8, 0x5d, 0x2e, 0xf2, 0x72, 0xbe, 0x90, 0xf4, 0x21, 0x2f, 0x24,
	0x5f, 0x26, 0x1f, 0x91, 0x28, 0xcb, 0xd7, 0xc9, 0xa6, 0xc8, 0x65, 0x9e, 0x90, 0x89, 0x8e, 0x05,
	0x97, 0x3c, 0xd6, 0x29, 0x16, 0xd8, 0x9c, 0x4a, 0x45, 0xdf, 0x60, 0x60, 0x1b, 0xd8, 0x01, 0x74,
	0x33, 0x11, 0x76, 0x26, 0x9d, 0xc3, 0xbd, 0xb4, 0x9b, 0x09, 0x36, 0x82, 0xbe, 0xcc, 0xe4, 0x12,
	0xc3, 0xae, 0x4e, 0x99, 0x80, 0x31, 0xe8, 0x09, 0xa4, 0x59, 0xe8, 0xe9, 0xa4, 0xfe, 0x66, 0x21,
	0x0c, 0x66, 0x05, 0x72, 0x89, 0x22, 0xec, 0x4d, 0x3a, 0x87, 0x5e, 0x5a, 0x85, 0xaa, 0x52, 0x6e,
	0x84, 0xae, 0xf4, 0x4d, 0xc5, 0x86, 0xd1, 0x05, 0x0c, 0x5f, 0x69, 0x50, 0x8a, 0x5f, 0x4b, 0x24,
	0xc9, 0x62, 0x18, 0xd8, 0xc5, 0xf4, 0x0e, 0xc1, 0xe9, 0x28, 0xde, 0x59, 0x34, 0xb6, 0x5b, 0xa6,
	0x15, 0x28, 0x7a, 0x06, 0x07, 0x15, 0x01, 0x6d, 0xf2, 0x35, 0xa1, 0x1a, 0xb6, 0x42, 0x22, 0x3e,
	0x47, 0x7b, 0x45, 0x15, 0x46, 0xc7, 0x30, 0x4c, 0x71, 0x95, 0xdf, 0xd4, 0xc3, 0x9e, 0xc0, 0x9e,
	0xe5, 0x79, 0x73, 0x69, 0xc1, 0xdb, 0x84, 0xa2, 0xae, 0xe0, 0x77, 0x52, 0x5f, 0xc0, 0xf0, 0x4a,
	0x9f, 0xf4, 0x1f, 0x77, 0x54, 0x04, 0x77, 0x0e, 0x3b, 0x82, 0x20, 0x45, 0x2e, 0x5a, 0xae, 0x10,
	0xee, 0x15, 0x22, 0x7a, 0x0e, 0xfb, 0x06, 0x6c, 0x69, 0xff, 0x75, 0xb1, 0x21, 0x04, 0x6f, 0x33,
	0x92, 0x76, 0x58, 0xf4, 0x02, 0xf6, 0x4d, 0x68, 0xe9, 0x4e, 0xe0, 0x9e, 0x45, 0x52, 0xd8, 0x99,
	0x78, 0xbf, 0xe5, 0xab, 0x51, 0xd1, 0x11, 0x3c, 0x50, 0x0c, 0x2f, 0x6f, 0xaf, 0x08, 0x8b, 0xea,
	0x86, 0x87, 0xe0, 0x97, 0x84, 0x45, 0x7d, 0x80, 0x8d, 0xa2, 0xf3, 0x0a, 0xfc, 0x29, 0x5b, 0xd5,
	0x6f, 0x3b, 0x82, 0x3e, 0x49, 0x5e, 0x48, 0x8d, 0xf5, 0x52, 0x13, 0xb0, 0xfb, 0xe0, 0xe1, 0x5a,
	0x68, 0x9b, 0x7a, 0xa9, 0xfa, 0x3c, 0xfd, 0xe1, 0x41, 0x60, 0xe7, 0x5f, 0x72, 0xc9, 0xd9, 0x14,
	0x7c, 0xe3, 0x15, 0x36, 0x6e, 0xec, 0xd8, 0x70, 0xe0, 0xf8, 0x71, 0x6b, 0xcd, 0x9e, 0x3b, 0x05,
	0xdf, 0x78, 0xc2, 0xa1, 0x68, 0xf8, 0xca, 0xa1, 0x70, 0x4c, 0x34, 0x05, 0xdf, 0x28, 0xed, 0x50,
	0x34, 0xfc, 0xe3, 0x50, 0x38, 0xd6, 0x38, 0x87, 0x9e, 0xd2, 0x94, 0x85, 0xce, 0x9c, 0xda, 0x13,
	0xe3, 0x47, 0x2d, 0x95, 0x6d, 0xb3, 0x7a, 0x52, 0xa7, 0x79, 0x47, 0x63, 0xa7, 0xb9, 0x21, 0xf7,
	0x6b, 0x80, 0xad, 0x78, 0xec, 0xe9, 0x2f, 0xc0, 0x86, 0xaa, 0x7f, 0x45, 0xa4, 0x84, 0x6d, 0x25,
	0xda, 0x51, 0xfc, 0x0f, 0x44, 0xd7, 0xbe, 0xfe, 0x9d, 0x9d, 0xfd, 0x0c, 0x00, 0x00, 0xff, 0xff,
	0x9f, 0xaa, 0xff, 0xbe, 0x21, 0x05, 0x00, 0x00,
}
